### ISSUE TITLE
Mongo connect path issue

### ISSUE THREAD

**Issue by moivica** [bunticj/dataTestingTool#26]
@bunticj , probably we need to handle cluster part on mongo db connect as env var also: 

```
mongoose.connect(`mongodb+srv://${process.env.MONGO_USER}:${process.env.MONGO_PW}@cluster0-kejbb.mongodb.net/${process.env.MONGO_DB}?retryWrites=true&w=majority`
```

pay attention to `@cluster0-kejbb.mongodb.net` part

**Comment by bunticj** [comment]
I don't have connection issues. Did you add  .env file ?    Have you pulled the latest code?

**Comment by moivica** [comment]
> I don't have connection issues. Did you add .env file ? Have you pulled the latest code?

Yep - but i created my own mongo db, and set those info in .env file. 

When i did that, it didn't work - connection could not been established. I've replaced this part `@cluster0-kejbb.mongodb.net` with my own info - and now everything works as it should.

![image](https://user-images.githubusercontent.com/31037172/70507823-78a85f00-1b2d-11ea-974f-c17f4f98d7e9.png)


Probably  `@cluster0-kejbb.mongodb.net`  should be treated as env var also...
